include:
  # boards
  - board: corneish_zen_v2_left
    # for dongle setup
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_DISPLAY=n

    # for zmk studio(remove for dongle setup)
    #snippet: studio-rpc-usb-uart
    #cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: corneish_zen_v2_right
    # for dongle setup
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # dongle
  - board: nice_nano_v2
    shield: corneish_zen_v2_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # bt settings reset
  - board: nice_nano_v2
    shield: settings_reset
